start /B python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\WallClock.py"
start /B python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\OrderQueue.py"
start /B python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\CashierQueue.py"
start python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\CustomerService.py"
start python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\cashier.py"
start python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\Barista.py"
start /B python "C:\Users\Sameer Ranade\Documents\GitHub\StarBucks\CreateCustomer.py"